// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OpinionsColumns holds the columns for the "opinions" table.
	OpinionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "asunto", Type: field.TypeString, Size: 2147483647},
		{Name: "contenido", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVO", "INACTIVO"}, Default: "ACTIVO"},
		{Name: "opinion_parent", Type: field.TypeInt, Nullable: true},
	}
	// OpinionsTable holds the schema information for the "opinions" table.
	OpinionsTable = &schema.Table{
		Name:       "opinions",
		Columns:    OpinionsColumns,
		PrimaryKey: []*schema.Column{OpinionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "opinions_opinions_parent",
				Columns:    []*schema.Column{OpinionsColumns[5]},
				RefColumns: []*schema.Column{OpinionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OpinionsTable,
	}
)

func init() {
	OpinionsTable.ForeignKeys[0].RefTable = OpinionsTable
}
