// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"opinion/ent/migrate"

	"opinion/ent/opinion"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Opinion is the client for interacting with the Opinion builders.
	Opinion *OpinionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Opinion = NewOpinionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Opinion: NewOpinionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Opinion: NewOpinionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Opinion.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Opinion.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Opinion.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OpinionMutation:
		return c.Opinion.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OpinionClient is a client for the Opinion schema.
type OpinionClient struct {
	config
}

// NewOpinionClient returns a client for the Opinion from the given config.
func NewOpinionClient(c config) *OpinionClient {
	return &OpinionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `opinion.Hooks(f(g(h())))`.
func (c *OpinionClient) Use(hooks ...Hook) {
	c.hooks.Opinion = append(c.hooks.Opinion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `opinion.Intercept(f(g(h())))`.
func (c *OpinionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Opinion = append(c.inters.Opinion, interceptors...)
}

// Create returns a builder for creating a Opinion entity.
func (c *OpinionClient) Create() *OpinionCreate {
	mutation := newOpinionMutation(c.config, OpCreate)
	return &OpinionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Opinion entities.
func (c *OpinionClient) CreateBulk(builders ...*OpinionCreate) *OpinionCreateBulk {
	return &OpinionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Opinion.
func (c *OpinionClient) Update() *OpinionUpdate {
	mutation := newOpinionMutation(c.config, OpUpdate)
	return &OpinionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OpinionClient) UpdateOne(o *Opinion) *OpinionUpdateOne {
	mutation := newOpinionMutation(c.config, OpUpdateOne, withOpinion(o))
	return &OpinionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OpinionClient) UpdateOneID(id int) *OpinionUpdateOne {
	mutation := newOpinionMutation(c.config, OpUpdateOne, withOpinionID(id))
	return &OpinionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Opinion.
func (c *OpinionClient) Delete() *OpinionDelete {
	mutation := newOpinionMutation(c.config, OpDelete)
	return &OpinionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OpinionClient) DeleteOne(o *Opinion) *OpinionDeleteOne {
	return c.DeleteOneID(o.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OpinionClient) DeleteOneID(id int) *OpinionDeleteOne {
	builder := c.Delete().Where(opinion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OpinionDeleteOne{builder}
}

// Query returns a query builder for Opinion.
func (c *OpinionClient) Query() *OpinionQuery {
	return &OpinionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOpinion},
		inters: c.Interceptors(),
	}
}

// Get returns a Opinion entity by its id.
func (c *OpinionClient) Get(ctx context.Context, id int) (*Opinion, error) {
	return c.Query().Where(opinion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OpinionClient) GetX(ctx context.Context, id int) *Opinion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChildren queries the children edge of a Opinion.
func (c *OpinionClient) QueryChildren(o *Opinion) *OpinionQuery {
	query := (&OpinionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := o.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(opinion.Table, opinion.FieldID, id),
			sqlgraph.To(opinion.Table, opinion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, opinion.ChildrenTable, opinion.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(o.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a Opinion.
func (c *OpinionClient) QueryParent(o *Opinion) *OpinionQuery {
	query := (&OpinionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := o.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(opinion.Table, opinion.FieldID, id),
			sqlgraph.To(opinion.Table, opinion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, opinion.ParentTable, opinion.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(o.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OpinionClient) Hooks() []Hook {
	return c.hooks.Opinion
}

// Interceptors returns the client interceptors.
func (c *OpinionClient) Interceptors() []Interceptor {
	return c.inters.Opinion
}

func (c *OpinionClient) mutate(ctx context.Context, m *OpinionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OpinionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OpinionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OpinionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OpinionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Opinion mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Opinion []ent.Hook
	}
	inters struct {
		Opinion []ent.Interceptor
	}
)
