// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"opinion/ent/opinion"
	"opinion/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OpinionDelete is the builder for deleting a Opinion entity.
type OpinionDelete struct {
	config
	hooks    []Hook
	mutation *OpinionMutation
}

// Where appends a list predicates to the OpinionDelete builder.
func (od *OpinionDelete) Where(ps ...predicate.Opinion) *OpinionDelete {
	od.mutation.Where(ps...)
	return od
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (od *OpinionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, OpinionMutation](ctx, od.sqlExec, od.mutation, od.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (od *OpinionDelete) ExecX(ctx context.Context) int {
	n, err := od.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (od *OpinionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opinion.Table, sqlgraph.NewFieldSpec(opinion.FieldID, field.TypeInt))
	if ps := od.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, od.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	od.mutation.done = true
	return affected, err
}

// OpinionDeleteOne is the builder for deleting a single Opinion entity.
type OpinionDeleteOne struct {
	od *OpinionDelete
}

// Where appends a list predicates to the OpinionDelete builder.
func (odo *OpinionDeleteOne) Where(ps ...predicate.Opinion) *OpinionDeleteOne {
	odo.od.mutation.Where(ps...)
	return odo
}

// Exec executes the deletion query.
func (odo *OpinionDeleteOne) Exec(ctx context.Context) error {
	n, err := odo.od.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opinion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (odo *OpinionDeleteOne) ExecX(ctx context.Context) {
	if err := odo.Exec(ctx); err != nil {
		panic(err)
	}
}
