// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"opinion/ent/opinion"
	"opinion/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OpinionQuery is the builder for querying Opinion entities.
type OpinionQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.Opinion
	withChildren *OpinionQuery
	withParent   *OpinionQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpinionQuery builder.
func (oq *OpinionQuery) Where(ps ...predicate.Opinion) *OpinionQuery {
	oq.predicates = append(oq.predicates, ps...)
	return oq
}

// Limit the number of records to be returned by this query.
func (oq *OpinionQuery) Limit(limit int) *OpinionQuery {
	oq.ctx.Limit = &limit
	return oq
}

// Offset to start from.
func (oq *OpinionQuery) Offset(offset int) *OpinionQuery {
	oq.ctx.Offset = &offset
	return oq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oq *OpinionQuery) Unique(unique bool) *OpinionQuery {
	oq.ctx.Unique = &unique
	return oq
}

// Order specifies how the records should be ordered.
func (oq *OpinionQuery) Order(o ...OrderFunc) *OpinionQuery {
	oq.order = append(oq.order, o...)
	return oq
}

// QueryChildren chains the current query on the "children" edge.
func (oq *OpinionQuery) QueryChildren() *OpinionQuery {
	query := (&OpinionClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(opinion.Table, opinion.FieldID, selector),
			sqlgraph.To(opinion.Table, opinion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, opinion.ChildrenTable, opinion.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (oq *OpinionQuery) QueryParent() *OpinionQuery {
	query := (&OpinionClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(opinion.Table, opinion.FieldID, selector),
			sqlgraph.To(opinion.Table, opinion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, opinion.ParentTable, opinion.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Opinion entity from the query.
// Returns a *NotFoundError when no Opinion was found.
func (oq *OpinionQuery) First(ctx context.Context) (*Opinion, error) {
	nodes, err := oq.Limit(1).All(setContextOp(ctx, oq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{opinion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oq *OpinionQuery) FirstX(ctx context.Context) *Opinion {
	node, err := oq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Opinion ID from the query.
// Returns a *NotFoundError when no Opinion ID was found.
func (oq *OpinionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(1).IDs(setContextOp(ctx, oq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{opinion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oq *OpinionQuery) FirstIDX(ctx context.Context) int {
	id, err := oq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Opinion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Opinion entity is found.
// Returns a *NotFoundError when no Opinion entities are found.
func (oq *OpinionQuery) Only(ctx context.Context) (*Opinion, error) {
	nodes, err := oq.Limit(2).All(setContextOp(ctx, oq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{opinion.Label}
	default:
		return nil, &NotSingularError{opinion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oq *OpinionQuery) OnlyX(ctx context.Context) *Opinion {
	node, err := oq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Opinion ID in the query.
// Returns a *NotSingularError when more than one Opinion ID is found.
// Returns a *NotFoundError when no entities are found.
func (oq *OpinionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(2).IDs(setContextOp(ctx, oq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{opinion.Label}
	default:
		err = &NotSingularError{opinion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oq *OpinionQuery) OnlyIDX(ctx context.Context) int {
	id, err := oq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Opinions.
func (oq *OpinionQuery) All(ctx context.Context) ([]*Opinion, error) {
	ctx = setContextOp(ctx, oq.ctx, "All")
	if err := oq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Opinion, *OpinionQuery]()
	return withInterceptors[[]*Opinion](ctx, oq, qr, oq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oq *OpinionQuery) AllX(ctx context.Context) []*Opinion {
	nodes, err := oq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Opinion IDs.
func (oq *OpinionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oq.ctx.Unique == nil && oq.path != nil {
		oq.Unique(true)
	}
	ctx = setContextOp(ctx, oq.ctx, "IDs")
	if err = oq.Select(opinion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oq *OpinionQuery) IDsX(ctx context.Context) []int {
	ids, err := oq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oq *OpinionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oq.ctx, "Count")
	if err := oq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oq, querierCount[*OpinionQuery](), oq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oq *OpinionQuery) CountX(ctx context.Context) int {
	count, err := oq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oq *OpinionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oq.ctx, "Exist")
	switch _, err := oq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oq *OpinionQuery) ExistX(ctx context.Context) bool {
	exist, err := oq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpinionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oq *OpinionQuery) Clone() *OpinionQuery {
	if oq == nil {
		return nil
	}
	return &OpinionQuery{
		config:       oq.config,
		ctx:          oq.ctx.Clone(),
		order:        append([]OrderFunc{}, oq.order...),
		inters:       append([]Interceptor{}, oq.inters...),
		predicates:   append([]predicate.Opinion{}, oq.predicates...),
		withChildren: oq.withChildren.Clone(),
		withParent:   oq.withParent.Clone(),
		// clone intermediate query.
		sql:  oq.sql.Clone(),
		path: oq.path,
	}
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OpinionQuery) WithChildren(opts ...func(*OpinionQuery)) *OpinionQuery {
	query := (&OpinionClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withChildren = query
	return oq
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OpinionQuery) WithParent(opts ...func(*OpinionQuery)) *OpinionQuery {
	query := (&OpinionClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withParent = query
	return oq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Asunto string `json:"asunto,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Opinion.Query().
//		GroupBy(opinion.FieldAsunto).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oq *OpinionQuery) GroupBy(field string, fields ...string) *OpinionGroupBy {
	oq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpinionGroupBy{build: oq}
	grbuild.flds = &oq.ctx.Fields
	grbuild.label = opinion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Asunto string `json:"asunto,omitempty"`
//	}
//
//	client.Opinion.Query().
//		Select(opinion.FieldAsunto).
//		Scan(ctx, &v)
func (oq *OpinionQuery) Select(fields ...string) *OpinionSelect {
	oq.ctx.Fields = append(oq.ctx.Fields, fields...)
	sbuild := &OpinionSelect{OpinionQuery: oq}
	sbuild.label = opinion.Label
	sbuild.flds, sbuild.scan = &oq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpinionSelect configured with the given aggregations.
func (oq *OpinionQuery) Aggregate(fns ...AggregateFunc) *OpinionSelect {
	return oq.Select().Aggregate(fns...)
}

func (oq *OpinionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oq); err != nil {
				return err
			}
		}
	}
	for _, f := range oq.ctx.Fields {
		if !opinion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oq.path != nil {
		prev, err := oq.path(ctx)
		if err != nil {
			return err
		}
		oq.sql = prev
	}
	return nil
}

func (oq *OpinionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Opinion, error) {
	var (
		nodes       = []*Opinion{}
		withFKs     = oq.withFKs
		_spec       = oq.querySpec()
		loadedTypes = [2]bool{
			oq.withChildren != nil,
			oq.withParent != nil,
		}
	)
	if oq.withParent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, opinion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Opinion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Opinion{config: oq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oq.withChildren; query != nil {
		if err := oq.loadChildren(ctx, query, nodes,
			func(n *Opinion) { n.Edges.Children = []*Opinion{} },
			func(n *Opinion, e *Opinion) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := oq.withParent; query != nil {
		if err := oq.loadParent(ctx, query, nodes, nil,
			func(n *Opinion, e *Opinion) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oq *OpinionQuery) loadChildren(ctx context.Context, query *OpinionQuery, nodes []*Opinion, init func(*Opinion), assign func(*Opinion, *Opinion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Opinion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Opinion(func(s *sql.Selector) {
		s.Where(sql.InValues(opinion.ChildrenColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.opinion_parent
		if fk == nil {
			return fmt.Errorf(`foreign-key "opinion_parent" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "opinion_parent" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (oq *OpinionQuery) loadParent(ctx context.Context, query *OpinionQuery, nodes []*Opinion, init func(*Opinion), assign func(*Opinion, *Opinion)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Opinion)
	for i := range nodes {
		if nodes[i].opinion_parent == nil {
			continue
		}
		fk := *nodes[i].opinion_parent
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(opinion.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "opinion_parent" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oq *OpinionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oq.querySpec()
	_spec.Node.Columns = oq.ctx.Fields
	if len(oq.ctx.Fields) > 0 {
		_spec.Unique = oq.ctx.Unique != nil && *oq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oq.driver, _spec)
}

func (oq *OpinionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(opinion.Table, opinion.Columns, sqlgraph.NewFieldSpec(opinion.FieldID, field.TypeInt))
	_spec.From = oq.sql
	if unique := oq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oq.path != nil {
		_spec.Unique = true
	}
	if fields := oq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opinion.FieldID)
		for i := range fields {
			if fields[i] != opinion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oq *OpinionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oq.driver.Dialect())
	t1 := builder.Table(opinion.Table)
	columns := oq.ctx.Fields
	if len(columns) == 0 {
		columns = opinion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oq.sql != nil {
		selector = oq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oq.ctx.Unique != nil && *oq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oq.predicates {
		p(selector)
	}
	for _, p := range oq.order {
		p(selector)
	}
	if offset := oq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpinionGroupBy is the group-by builder for Opinion entities.
type OpinionGroupBy struct {
	selector
	build *OpinionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ogb *OpinionGroupBy) Aggregate(fns ...AggregateFunc) *OpinionGroupBy {
	ogb.fns = append(ogb.fns, fns...)
	return ogb
}

// Scan applies the selector query and scans the result into the given value.
func (ogb *OpinionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ogb.build.ctx, "GroupBy")
	if err := ogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpinionQuery, *OpinionGroupBy](ctx, ogb.build, ogb, ogb.build.inters, v)
}

func (ogb *OpinionGroupBy) sqlScan(ctx context.Context, root *OpinionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ogb.fns))
	for _, fn := range ogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ogb.flds)+len(ogb.fns))
		for _, f := range *ogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpinionSelect is the builder for selecting fields of Opinion entities.
type OpinionSelect struct {
	*OpinionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (os *OpinionSelect) Aggregate(fns ...AggregateFunc) *OpinionSelect {
	os.fns = append(os.fns, fns...)
	return os
}

// Scan applies the selector query and scans the result into the given value.
func (os *OpinionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, os.ctx, "Select")
	if err := os.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpinionQuery, *OpinionSelect](ctx, os.OpinionQuery, os, os.inters, v)
}

func (os *OpinionSelect) sqlScan(ctx context.Context, root *OpinionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(os.fns))
	for _, fn := range os.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*os.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := os.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
