// Code generated by ent, DO NOT EDIT.

package ent

import (
	"opinion/ent/opinion"
	"opinion/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	opinionFields := schema.Opinion{}.Fields()
	_ = opinionFields
	// opinionDescAsunto is the schema descriptor for asunto field.
	opinionDescAsunto := opinionFields[0].Descriptor()
	// opinion.AsuntoValidator is a validator for the "asunto" field. It is called by the builders before save.
	opinion.AsuntoValidator = opinionDescAsunto.Validators[0].(func(string) error)
	// opinionDescContenido is the schema descriptor for contenido field.
	opinionDescContenido := opinionFields[1].Descriptor()
	// opinion.ContenidoValidator is a validator for the "contenido" field. It is called by the builders before save.
	opinion.ContenidoValidator = opinionDescContenido.Validators[0].(func(string) error)
	// opinionDescCreatedAt is the schema descriptor for created_at field.
	opinionDescCreatedAt := opinionFields[2].Descriptor()
	// opinion.DefaultCreatedAt holds the default value on creation for the created_at field.
	opinion.DefaultCreatedAt = opinionDescCreatedAt.Default.(func() time.Time)
}
